"""
Created on Thu Aug  7 12:58:09 2014

@author: rkp

Functions for managing arrays
"""

import numpy as np
from scipy.linalg import toeplitz

def sliding_window(x, n, start=0, end=None):
    """Generate a 2D array where rows are generated by sliding a window along
    1D array x.
    
    Args:
        x: 1D array
        n: size of window
        start: starting index
        
    Example:
        >>> x = np.arange(15)
        >>> sliding_window(x, 3)
        array([[ 0,  1,  2],
               [ 1,  2,  3],
               [ 2,  3,  4],
               [ 3,  4,  5],
               [ 4,  5,  6],
               [ 5,  6,  7],
               [ 6,  7,  8],
               [ 7,  8,  9],
               [ 8,  9, 10],
               [ 9, 10, 11],
               [10, 11, 12],
               [11, 12, 13],
               [12, 13, 14]])
        >>> sliding_window(x, 3, 7)
        array([[ 7,  8,  9],
               [ 8,  9, 10],
               [ 9, 10, 11],
               [10, 11, 12],
               [11, 12, 13],
               [12, 13, 14]])
    """
    
    full_matrix = np.fliplr(toeplitz(x[n-1:], x[:n][::-1]))
    
    return full_matrix[start:end,:]  